### ISSUE TITLE
[Bug] 无法扫描到带有中括号的章节名

### ISSUE THREAD

**Issue by spr-equinox** [Zeal-L/BiliBili-Manga-Downloader#100]
### 问题描述

在glob表达式中，中括号会被转义

漫画名：关于我转生变成史莱姆这档事 异闻～在魔国生活的三位一体～
章节名：第42话 奔跑吧，布鲁姆特 [之一]

### 预期行为

略

### 实际行为

略

### 哔哩哔哩漫画下载器版本号

v1.5.0

### 系统环境

Windows10

### 日志

略

**Comment by shadlc** [comment]
已处理
