### ISSUE TITLE
[Bug] 更新1.5版本CPU占用极高

### ISSUE THREAD

**Issue by kerriajaponica** [Zeal-L/BiliBili-Manga-Downloader#102]
### 问题描述

1.5版本下载器启动和下载时的CPU占用都高的爆炸,而且下载速度也变慢了

### 预期行为

和1.4版本一样或者更优的CPU占用和下载速度

### 实际行为

1.5版本下载器启动的时候会吃满CPU占用,下载的时候会占80%,下载速度也只剩2MB/s了,同样网络环境1.4版本CPU只占用10%,而且下载速度有10MB/s左右

### 截图或录屏

1.5版本启动和下载占用
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/fbd9fa26-331d-46c1-991f-1334a7afedf9)
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/dce8d424-6b21-4b52-8a74-b3e5bbdd308b)
1.4版本下载占用
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/00837be0-9128-4fdc-a2bd-3cd4b839ca56)

### 哔哩哔哩漫画下载器版本号

v1.5.0

### 系统环境

Windows10

### 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/13651424/ERROR.log)

**Comment by Zeal-L** [comment]
@kerriajaponica 这个下载速度应该是一致的，之前版本的下载速度不准确，有越来越大的趋势
至于这个cpu高占用等我周末有时间了细看一下，谢谢反馈~

**Comment by kerriajaponica** [comment]
不是那个显示bug,是下载速度真的肉眼可见慢了很多,我看的是代理里的网速不是下载器里显示的,不过可能跟CPU占用是一起的问题.
改成1线程下载之后占用10%,但是同样单线程下载1.5版本也比1.4速度慢.
1.5版本1线程和8线程速度
![屏幕截图 2023-12-14 181724](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/98c9c3ee-f6e9-4945-8ddb-2eaa17f436fb)
![屏幕截图 2023-12-14 181731](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/88e7a456-83ce-462f-a48d-3325c617f09b)
1.4版本1线程和8线程速度
![屏幕截图 2023-12-14 182342](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/a71d8103-ef58-48df-b576-d6d5e1661adf)
![屏幕截图 2023-12-14 182149](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/63228002/3777e517-cc1b-4350-b87a-4e5f08ca7ecb)

**Comment by bingsunny0730** [comment]
2个月之后的今天体验下来，下载十几个章节时确实CPU直接拉满，严重时光标移动界面直接卡掉帧，大佬何时优化改良下代码呀？？
![sshot-18989713333 bug](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/131505889/e8f3a63e-6067-4859-b09b-f724289ae536)

**Comment by Zeal-L** [comment]
@kerriajaponica @bingsunny0730 新版本 v1.5.1 的使用情况有没有改善呢？

**Comment by shadlc** [comment]
无处理计划
