### ISSUE TITLE
[功能请求] 能否实现弹幕文件以及评论文件的存储

### ISSUE THREAD

**Issue by arashi-knight** [Zeal-L/BiliBili-Manga-Downloader#103]
### 原因

毕竟b站漫画的一个特点就是图片上的弹幕，如果能够实现弹幕或者评论的存储，在后期观看的时候说不定也能多几分乐趣

### 功能简述

弹幕理论上保存的是坐标以及内容，可以作为一个单独的json文件保存在每一章的文件夹内部，将来可以在阅读器上做适配

ps：如果添加，建议加一个为已保存的漫画补充下载弹幕/评论的选项，以及下载时是否保存弹幕/评论的选项

### 功能逻辑

//

**Comment by Zeal-L** [comment]
抱歉，这个跟漫画浏览器的关联太强了，不能确定具体格式，暂不考虑
