### ISSUE TITLE
Avast杀毒拦截

### ISSUE THREAD

**Issue by AuspiceGwan** [Zeal-L/BiliBili-Manga-Downloader#107]
### 问题描述

在装有Avast反病毒的电脑上，程序会被隔离，最新版1.5.0报告为Win64:Malware-Gen，旧版报告Win64:Evo-Gen

### 预期行为

不应有病毒报错

### 实际行为

反病毒拦截报错

### 哔哩哔哩漫画下载器版本号

v1.5.0

### 系统环境

Windows10

### 日志

因未正常启动，故无日志

**Comment by Zeal-L** [comment]
@AuspiceGwan  这是来自 [pyinstaller](https://github.com/pyinstaller/pyinstaller/issues) 的上游问题
由于我们的依赖项太新了，每次发布版本时都会发生这种情况。仅记住校验和的较笨的抗病毒软件需要一段时间才能赶上。
