### ISSUE TITLE
[功能请求] 可不可以搞一个下载已下架漫画的功能，就是账号已经购买了，但是漫画下架了，漫画还能查看，所以应该还有办法下下来

### ISSUE THREAD

**Issue by c870620096** [Zeal-L/BiliBili-Manga-Downloader#108]
### 原因

目前的搜索功能搜索不到下架的漫画，但是账号已经购买是可以在库存查看的

### 功能简述

可不可以搞一个下载已下架漫画的功能。已经购买了的漫画，虽然漫画下架了，但是漫画还能查看，所以应该还有办法下下来

### 功能逻辑

可以做一个选项，或者添加另一条途径去搜索

### 实现参考

定位到该账号的已购买的库存，然后爬下来

**Comment by Zeal-L** [comment]
@c870620096 这个功能已经实现了啊，哈哈哈，只有有漫画ID就可以下载
