### ISSUE TITLE
打不开软件怎么办

### ISSUE THREAD

**Issue by pinkxxy** [Zeal-L/BiliBili-Manga-Downloader#109]
### 问题描述

打不开软件怎么办

### 预期行为

打开

### 实际行为

打不开

Failed to execute script 'app' due to unhandledexception: Invalid header value
b'SESSDATA=e955d243%2C1720266150%2C20fa2

Traceback (most recent call last):
  File "app.py", line 24, in <module>
  File "src\ui\MainGUI.py", line 72, in __init__
  File "src\ui\MangaUI.py", line 61, in __init__
  File "src\ui\MangaUI.py", line 173, in init_myLibrary
  File "src\ui\MangaUI.py", line 237, in updateMyLibrary
  File "src\ui\MangaUI.py", line 238, in <listcomp>
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "src\ui\MangaUI.py", line 260, in updateMyLibrarySingle
  File "src\Comic.py", line 78, in getComicInfo
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\Comic.py", line 61, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 496, in _make_request
  File "urllib3\connection.py", line 394, in request
  File "urllib3\connection.py", line 308, in putheader
  File "http\client.py", line 1264, in putheader
ValueError: Invalid header value b'SESSDATA=e955d243%2C1720266150%2C20fa2%2A11CjBkaTjmhC7nVGgY9JPMPYag4fYku8Xamq2TSv-AUCu5YwvH6-t3aZq8RvlX88DI-CkSVkM3QXpsRFRIMjFXTVY5dF8wRjQyX0VWRDUwWmYzRWwtNW5DcjJHWWplYkJ4XzRIbHJIcmNlQW9oSGlsTExKZmI5WlBLTVd0MXhtYWhBYTJiYW42bFJBIIEC\n'

### 哔哩哔哩漫画下载器版本号

1.4.0

### 系统环境

Windows10

### 日志

			-------------------  程序正常退出 -------------------

21:46:49 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:46:49 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
21:47:17 | INFO | Comic: getComicCover - 123 | 获取《NANA世上的另一个我》的封面图片中...
21:47:20 | INFO | Comic: getComicCover - 123 | 获取《NANA世上的另一个我》的封面图片中...
21:47:32 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

21:47:46 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:47:46 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
21:47:47 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:47:47 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
21:47:51 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

21:48:31 | ERROR | MainGUI: closeEvent - 101 | 清除用户数据失败 - 目录:C:\Users\pinkx\AppData\Roaming\BiliBili-Manga-Downloader
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\pinkx\\AppData\\Roaming\\BiliBili-Manga-Downloader\\logs\\ERROR.log'
21:48:31 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

21:48:40 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:48:40 | INFO | MainGUI: __init__ - 68 | save_method: None
21:49:28 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
21:49:39 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
21:49:55 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
21:50:02 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:50:02 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
21:50:37 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
21:53:03 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:53:03 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
21:53:57 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
21:54:07 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:03:03 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:03:10 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:03:10 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:03:21 | WARNING | Comic: _ - 69 | 漫画id:28202 获取漫画信息失败! 重试中...
HTTPSConnectionPool(host='manga.bilibili.com', port=443): Read timed out. (read timeout=2)
22:03:34 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:03:50 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:04:17 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:04:17 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:13:34 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:13:42 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:13:42 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:15:22 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:15:30 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:15:30 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:15:48 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:16:04 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:16:04 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:16:12 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:16:12 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:16:16 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:16:20 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:16:34 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:16:36 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:16:49 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:17:23 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:17:23 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:21:06 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:21:27 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:21:27 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:21:40 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:21:57 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:23:25 | INFO | SearchComic: getResults - 61 | 正在搜索漫画:《nana》中...
22:23:41 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:23:41 | INFO | MainGUI: closeEvent - 103 | 

			-------------------  程序正常退出 -------------------

22:25:02 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:25:02 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:25:02 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:25:02 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:25:08 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:25:08 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:26:00 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:26:00 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:26:40 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:26:40 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:26:49 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:26:49 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:27:16 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:27:16 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:27:20 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:27:20 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:27:52 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:27:52 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:31:03 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:31:03 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:31:14 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:31:14 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:38:42 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:38:42 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:43:30 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:43:30 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:43:35 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:43:35 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:44:26 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:44:26 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:44:28 | WARNING | Comic: _ - 68 | 漫画id:26416 获取漫画信息失败! 重试中...
HTTPSConnectionPool(host='manga.bilibili.com', port=443): Read timed out. (read timeout=2)
22:45:32 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:45:32 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:45:38 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:45:38 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:46:47 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:46:47 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:46:51 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:46:51 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:47:02 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:47:02 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:47:06 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:47:06 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:47:07 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:47:07 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:48:50 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:48:50 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:51:16 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:51:16 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:51:25 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:51:25 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
22:51:36 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

22:51:36 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片

**Comment by Zeal-L** [comment]
@pinkxxy  你尝试一下把缓存文件夹全部删掉再重新打开软件
