### ISSUE TITLE
[功能请求] Docker形式的存在+自动追漫功能

### ISSUE THREAD

**Issue by mhqschen** [Zeal-L/BiliBili-Manga-Downloader#113]
### 原因

一直想要有个自动下载漫画的方式。这个需要有图源+工具。现在看下来BiliPlus是个不错的图源。就差工具了。

### 功能简述

Docker形式部署，后台自动检测更新，自动下载，下载完后通过bark等渠道通知用户。

### 功能逻辑

一个简单的webui配置cookie，需要追的漫画，保存路径和保存格式。初次下载可以选择下载全部，下载最新一话，还是下载最近X话。命令行形式的交互甚至手搓配置文件形式也可以。

**Comment by Zeal-L** [comment]
@mhqschen 
爬取漫画的主逻辑和UI部分已经解耦的比较彻底了, 基本就是下面三个脚本
- [Comic.py](https://github.com/Zeal-L/BiliBili-Manga-Downloader/blob/f5a06f9b7d10912d7a77b2852511cec1d7a0b9bc/src/Comic.py)
- [Episode.py](https://github.com/Zeal-L/BiliBili-Manga-Downloader/blob/f5a06f9b7d10912d7a77b2852511cec1d7a0b9bc/src/Episode.py)
- [BiliPlus.py](https://github.com/Zeal-L/BiliBili-Manga-Downloader/blob/f5a06f9b7d10912d7a77b2852511cec1d7a0b9bc/src/BiliPlus.py)

你可以自己包装一层命令行形式，然后build docker
或者你也可以看看本项目的最初一个push，在那里我也实现了一个简易的命令行交互界面
你的需求和本项目目前的呈现形式偏差过大，cause wont help, sorry
