### ISSUE TITLE
[功能请求] 能添加一个全选、反选功能吗

### ISSUE THREAD

**Issue by Ghostbullets** [Zeal-L/BiliBili-Manga-Downloader#114]
### 原因

想要下载漫画的所有可下载章节，不然一个个点√好痛苦

### 功能简述

能添加一个全选、反选功能吗，想要下载漫画的所有可下载章节，不然一个个点√好痛苦

### 功能逻辑

点击全选选中所有可下载章节，点击反选可可以将当前选中章节取消，并选中其他章节

**Comment by Zeal-L** [comment]
@Ghostbullets 最新的版本1.5启动页面有小技巧提示的
你鼠标右键就有全选选项
