### ISSUE TITLE
[功能请求] 导出为PDF/EPUB（逐话/全本）的功能

### ISSUE THREAD

**Issue by NatsumiXD** [Zeal-L/BiliBili-Manga-Downloader#117]
### 原因

方便下载与备份，在阅读器上也能够拥有更好的体验

### 功能简述

带有 **目录** 的PDF或者EPUB格式，并且支持逐话/全本导出

### 功能逻辑

选中想要导出的章节，选择 "逐话导出"或“全本导出”选项，然后开始导出

**Comment by Zeal-L** [comment]
emmm 你的意思是全部合并成一个 pdf 吗，那例如海贼王 1000 多话，一个 pdf 就要上 10g 了。不太科学吧，我难以想象它的打开速度
如果你真的有这方面的需求，用第三方的 pdf 合并工具可能更加合适一些

**Comment by NatsumiXD** [comment]
> emmm 你的意思是全部合并成一个 pdf 吗，那例如海贼王 1000 多话，一个 pdf 就要上 10g 了。不太科学吧，我难以想象它的打开速度 如果你真的有这方面的需求，用第三方的 pdf 合并工具可能更加合适一些

所以可以通过话数来合并啊（
