### ISSUE TITLE
[功能请求] 能否加入不下载每章节末尾章节信息图片的功能

### ISSUE THREAD

**Issue by fsoceityC** [Zeal-L/BiliBili-Manga-Downloader#118]
### 原因

看漫画的时候更简洁

### 功能简述

不下载或者删除每章节页面末尾的1-2章信息图片，长这样，有的章节只有最后一张，没有倒数第二张
![Snipaste_2024-03-05_23-44-21](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/89299632/d7f9b844-dddd-4468-828f-2d83ab42a4d0)

### 功能逻辑

提供一个开关可以选择是否开启

### 实现参考

自动不下载最后一张图片即可，但是对于有两张图片的章节需要识别，可否通过图片文件名或者接口信息识别？如果不行，只不下载最后一张图片也可以完成基本需求。

**Comment by Zeal-L** [comment]
图片文件名都是标准的序号，没有额外信息可以用来判断，而且也不是所有漫画最后一页都是广告。
这个功能很难实现，ai 识图太重了，暂不考虑
目前请先使用文件夹-图片的形式下载，自行删除吧
