### ISSUE TITLE
[Bug] Token无效

### ISSUE THREAD

**Issue by crazywheel** [Zeal-L/BiliBili-Manga-Downloader#119]
### 问题描述

你好，提示获取的Token无效导致失败是怎么回事？

### 预期行为

正常下载

### 实际行为

无法连续下载

### 哔哩哔哩漫画下载器版本号

V1.5.0

### 系统环境

Windows10

### 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/14523416/ERROR.log)

**Comment by Zeal-L** [comment]
@crazywheel 你尝试一下去官网重新获取 biliplus token 吧，可能是之前的过期了

**Comment by crazywheel** [comment]
不好意思，问一下是哪个官网？

**Comment by crazywheel** [comment]
> @crazywheel 你尝试一下去官网重新获取 biliplus token 吧，可能是之前的过期了

麻烦问下是哪个官网？

**Comment by Zeal-L** [comment]
> > @crazywheel 你尝试一下去官网重新获取 biliplus token 吧，可能是之前的过期了
> 
> 麻烦问下是哪个官网？

[biliplus](https://www.biliplus.com/manga/)

![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/72005386/2f352078-16e0-4c17-a4ae-3b7d8c66f8a9)
