### ISSUE TITLE
[Bug] BiliPlus解析突然无法解析任何章节

### ISSUE THREAD

**Issue by van-lee-fxp** [Zeal-L/BiliBili-Manga-Downloader#125]
### 问题描述

今天晚上使用的时候发现用biliplus突然无法解析任何章节，前面几天尝试的时候都是能正常解析的今天突然不行了。我确认过自己的biliplus cookie是有效的。

### 预期行为

正常解析并返回biliplus解析的全部章节

### 实际行为

弹窗提示“biliplus无法解析任何章节”

### 截图或录屏

![哔哩哔哩漫画下载器_g4cezwhFdp](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/146909397/133b7514-179f-4487-8771-0006ae5a4c9e)

### 哔哩哔哩漫画下载器版本号

v1.5.0

### 系统环境

Windows11

### 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/14774605/ERROR.log)

**Comment by van-lee-fxp** [comment]
看到BiliPlus的网站上说“bilibili漫画已更换链接授权规则，不同用户之间无法查看其他读者缓存的图片地址”，是不是这个原因？可能以后得另想办法解决？考虑让已经购买过并使用这个工具下载过的读者下载的结果缓存？

![waterfox_IPqYiZtTJ1](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/146909397/19bdf2b9-ffdc-467d-9aa3-f64f421d7a9e)

**Comment by KleinMoretti1** [comment]
我也是这样，确认界面提示cookie没错，解析的时候报这个错误

**Comment by Zeal-L** [comment]
**是的，很遗憾，被叔叔制裁了
黑科技下载暂时寄掉了
这个issue将会无期限open，直到新的火种出现！**
![12-11-10](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/72005386/e5caf198-bf31-4646-b8b5-dbe4011698e0)

**Comment by Zeal-L** [comment]
@van-lee-fxp @KleinMoretti1 没想到这才过去几天，已经正式复活了！快去下载新版本使用吧～

[**v1.5.1**](https://github.com/Zeal-L/BiliBili-Manga-Downloader/releases/tag/v1.5.1)

**Comment by van-lee-fxp** [comment]
太好了~终于可以继续追【我推】了~

**Comment by KleinMoretti1** [comment]
> @van-lee-fxp @KleinMoretti1 没想到这才过去几天，已经正式复活了！快去下载新版本使用吧～
> 
> [**v1.5.1**](https://github.com/Zeal-L/BiliBili-Manga-Downloader/releases/tag/v1.5.1)

大佬太强啦！！！

**Comment by hurriedlu** [comment]
> @van-lee-fxp @KleinMoretti1 没想到这才过去几天，已经正式复活了！快去下载新版本使用吧～
> 
> [** V1.5.1版**](https://github.com/Zeal-L/BiliBili-Manga-Downloader/releases/tag/v1.5.1)

大佬牛皮，令我的硬盘继续旋转
