### ISSUE TITLE
BiliPlus的Cookie一直报错

### ISSUE THREAD

**Issue by ke-xi** [Zeal-L/BiliBili-Manga-Downloader#135]
### 问题描述

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/14896200/ERROR.log)

### 预期行为

重新登录好几次了

### 实际行为

报错

### 截图或录屏

<img width="864" alt="Snipaste_2024-04-07_15-56-08" src="https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/58284266/1df3a874-7d4a-4d05-aa1d-cb314d66f8f4">

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows11

### 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/14896202/ERROR.log)

**Comment by Zeal-L** [comment]
https://github.com/Zeal-L/BiliBili-Manga-Downloader/discussions/129#discussioncomment-9020557
