### ISSUE TITLE
[功能请求] 点击“下载选中章节”后 增加一个提示

### ISSUE THREAD

**Issue by fuyn101** [Zeal-L/BiliBili-Manga-Downloader#136]
### 原因

没有提示的话，我会突然忘记自己点没点过这个按钮，然后点第二次（虽然我观察到并不会继续下载，但是我还是会惯性的看一眼下载列表）

### 功能简述

点击“下载选中章节”后 增加一个提示 
比如显示“ 已成功添加进下载列表”

### 功能逻辑

点击“下载选中章节”按钮 然后提示  “ 已成功添加进下载列表”

### 实现参考

![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/151902446/d0b25e58-7755-405a-9180-646b95c90f0f)

**Comment by Zeal-L** [comment]
@fuyn101 
现在的逻辑应该是点击下载后直接跳转到下载列表界面，并且回到章节详情的时候正在下载的章节已经变灰不可选了，我认为无需再加提示
