### ISSUE TITLE
[Bug]新版本与旧版本部分漫画命名规则变化导致本地库存识别失败

### ISSUE THREAD

**Issue by Leooone** [Zeal-L/BiliBili-Manga-Downloader#138]
### 问题描述

1、部分漫画整体命名规则变化，旧版本中命名为"第n话 xxx"，新版本中命名变为“n xxx”
2、部分漫画中带“·”的命名规则变化，原来版本命名为“第n话·m”，新版本中命名变为“n·m”

### 预期行为

1、“n xxx”命名变为正常的"第n话 xxx"
2、“n·m”命名变为正常的“第n话·m”

另外期望为每一话增加添加序号排序的选项，仅用名称排序，“番外篇”的顺序永远排在最后，与实际顺序不符

### 实际行为

版本间命名规则变化，命名规则不统一，漫画软件按名称排序会得到错误的漫画顺序

### 截图或录屏

![Snipaste_2024-04-12_22-02-36](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/31887209/1ef0fcbf-ba78-4042-8010-1a3d0b4b38b6)
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/31887209/f4f65e88-841e-4adc-8be9-14d1ace8ba7c)

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows11

### 日志

无

**Comment by Leooone** [comment]
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/31887209/5c56ccf9-4a37-48f7-bfb0-a1b7391226b9)
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/31887209/f94874b3-5c84-452a-8c4c-5e221833b5bc)

数字后接“()”“sp”等字符的具有相同的问题

**Comment by Zeal-L** [comment]
@Leooone 
- 标题问题应该是这个提交导致的https://github.com/Zeal-L/BiliBili-Manga-Downloader/pull/122 ,合并的时候确实忘记了会导致老库存读取错误的问题，哪种更合理我还需要再看看，不过无论如何都不可能适配所有漫画的章节格式
- 至于加序号，十分抱歉，一直打算做但是没有时间，如果做出来那肯定是能向前兼容，不影响库存读取的形式，请再期待一下吧，orz

**Comment by Zeal-L** [comment]
@spr-equinox 你要不要也来看看这个case~

**Comment by Zeal-L** [comment]
是的，我也觉得不可能找出所有特殊情况，所以有能力的话最好是自己写个脚本批量改一下老的，新老版本的正则表达式在https://github.com/Zeal-L/BiliBili-Manga-Downloader/pull/122 的更改记录里都有，这个任务我相信chatgpt就能搞定。
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/72005386/89a3acd7-cc12-4adf-8fea-5041dd34bf2e)

实在不行，你又很介意的话，也可以考虑删掉重新下载

**Comment by Zeal-L** [comment]
没问题就先关闭了哈
