### ISSUE TITLE
[功能请求] 增加intel版macOS支持

### ISSUE THREAD

**Issue by zzzyyyfffzyf** [Zeal-L/BiliBili-Manga-Downloader#141]
### 原因

目前手边还是18年的intel的MacBook，希望大大能发布个intel版的

### 功能简述

支持intel版MacBook的app

### 功能逻辑

直接安装在intel芯片的Mac本上

**Comment by Zeal-L** [comment]
https://github.com/Zeal-L/BiliBili-Manga-Downloader/issues/133
不好意思，我手边也没有机器
