### ISSUE TITLE
[Bug] 1.5.1版本修改主题后无法再次修改

### ISSUE THREAD

**Issue by ColorRain-Tree** [Zeal-L/BiliBili-Manga-Downloader#161]
### 问题描述

将主题样式从默认修改为其它后，主题样式区的选项框消失。重启应用也无法解决，只能重置用户数据。

### 预期行为

主题样式修改后能够再次修改。

### 实际行为

将主题样式从默认修改为其它后，主题样式区的选项框消失。重启应用也无法解决，只能重置用户数据。

### 截图或录屏

修改前：
![屏幕截图 2024-08-10 102230](https://github.com/user-attachments/assets/51e8f3d7-e8ff-4820-a340-8843c2e8fa69)
修改后：
![屏幕截图 2024-08-10 102327](https://github.com/user-attachments/assets/151148d6-0a37-4165-8a39-68625bf9f02a)

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows11

### 日志

[ERROR.log](https://github.com/user-attachments/files/16568205/ERROR.log)

**Comment by shadlc** [comment]
该问题为节目显示错误，因为其它主题其实并没有被完整测试，不建议切换，提供两个临时解决方案
1. 继续增加窗口高度，即可看到主题样式修改下拉框
2. 进入目录“C:\Users\{{用户名}}\AppData\Roaming\BiliBili-Manga-Downloader\config.json”将theme_style修改为"default"并重启软件
