### ISSUE TITLE
添加Biliplus的cookies后使用BiliPlus解析功能无法实现README文档同样效果

### ISSUE THREAD

**Issue by G1a0** [Zeal-L/BiliBili-Manga-Downloader#165]
### 问题描述

在正常添加BiliPlus的cookies之后尝试使用BiliPlus解析功能解析漫画，可以将漫画解析出来，但是无法实现README文档中的全部解锁效果。
![Snipaste_2024-09-07_11-58-40](https://github.com/user-attachments/assets/c395d41f-e176-425a-a264-6753bfd40b28)

### 预期行为

预计会显示漫画的可下载选项

### 实际行为

未如预期显示

### 截图或录屏

无

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows10

### 日志

C:\Users\你的用户名\AppData\Roaming\BiliBili-Manga-Downloader\logs\ERROR.log

**Comment by shadlc** [comment]
#168
解决方案：计划修改描述与README
