### ISSUE TITLE
[Bug] biliplus解析后没有更多章节，没之前解析的效果了

### ISSUE THREAD

**Issue by Dovahlore** [Zeal-L/BiliBili-Manga-Downloader#168]
### 问题描述

biliplus失效

### 预期行为

有解析更多章节

### 实际行为

仍是免费章节

### 截图或录屏

![image](https://github.com/user-attachments/assets/13d4f857-ae1f-4231-99e9-2bfd335d2dec)

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows11

### 日志

			-------------------  程序正常退出 -------------------

14:40:08 | INFO | MainGUI: __init__ - 56 | 

			------------------- 程序启动，初始化主窗口 -------------------

14:40:08 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
14:40:13 | INFO | SearchComic: getResults - 63 | 正在搜索漫画:《葬送》中...
14:40:14 | INFO | SearchComic: getResults - 77 | 搜索结果数量:3
14:40:16 | INFO | Comic: getComicCover - 129 | 获取《葬送的芙莉莲》的封面图片中...
14:40:29 | INFO | Comic: getComicCover - 129 | 获取《葬送的芙莉莲》的封面图片中...

**Comment by Dovahlore** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Kellyhjdajkfdhjkacn** [comment]
是的，我也是，biliplus解析没有任何多余解锁的章节

**Comment by Dovahlore** [comment]
我加入这个仓库所有者的Q群说是被B站方，面针对了。

**Comment by Dovahlore** [comment]
> 是的，我也是，biliplus解析没有任何多余解锁的章节

我加入这个仓库所有者的Q群说是被B站方，面针对了。

**Comment by Lawrence-of-AnKing** [comment]
同样没有解锁章节，还是来晚一步

**Comment by tomto0810** [comment]
这个功能未来还有可能整好吗。。。。不然我用这个也没意义了

**Comment by shadlc** [comment]
> 这个功能未来还有可能整好吗。。。。不然我用这个也没意义了

因不可抗力，biliplus那边分享的人少了，导致解锁章节骤降，我们的目标是做好一个下载器应该做的事情，如果有新的解决方案，欢迎提issue
