### ISSUE TITLE
up怎么才能下载已经下架的漫画呢

### ISSUE THREAD

**Issue by ZhouJie2090** [Zeal-L/BiliBili-Manga-Downloader#30]
我之前购买了<笨女孩>，我是可以从“我的已购”进入进行观看的，但是无法查看漫画详情页，无法下载。bilibili漫画搜索也搜不到，所以我想请问一下这个该怎么解决呢？笨女孩漫画id是mc26397

**Comment by Zeal-L** [comment]
这个目前好像不太好解决，已购被删只能在移动端上阅读。本软件是爬的是网页端。

**Comment by Zeal-L** [comment]
刚刚重新实验了一下，好像可以直接依靠漫画id读到被下架的漫画。也成功下载了。等下一个版本会发布此功能。

**Comment by Zeal-L** [comment]
@ZhouJie2090 可以了哦，快下载新版本试试吧！
![image](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/72005386/90799d0c-3cd1-4f3f-8315-bbfd6ab78ac2)

**Comment by ZhouJie2090** [comment]
太牛了太牛了，我这就去下载最新版。没想到up还在持续更新
从 Windows 版邮件发送

发件人: Zeal
发送时间: 2023年8月29日 22:33
收件人: Zeal-L/BiliBili-Manga-Downloader
抄送: Jie Zhou; Mention
主题: Re: [Zeal-L/BiliBili-Manga-Downloader] up怎么才能下载已经下架的漫画呢 (Issue #30)

@ZhouJie2090 可以了哦，快下载新版本试试吧！

**Comment by BalladeIris** [comment]
> 我之前购买了<笨女孩>，我是可以从“我的已购”进入进行观看的，但是无法查看漫画详情页，无法下载。bilibili漫画搜索也搜不到，所以我想请问一下这个该怎么解决呢？笨女孩漫画id是mc26397

请问这个漫画id是怎么查询到的呀？

**Comment by ZhouJie2090** [comment]
> > 我之前购买了<笨女孩>，我是可以从“我的已购”进入进行观看的，但是无法查看漫画详情页，无法下载。bilibili漫画搜索也搜不到，所以我想请问一下这个该怎么解决呢？笨女孩漫画id是mc26397
> 
> 请问这个漫画id是怎么查询到的呀？

这个我是从已购漫画里进去的，网页上可以看到id，其他下架的我也不知道怎么查看
