### ISSUE TITLE
[功能请求] 建议添加章节框选功能，建议添加下载漫画元数据的功能

### ISSUE THREAD

**Issue by arashi-knight** [Zeal-L/BiliBili-Manga-Downloader#39]
### 原因

章节目前只有点选和全选功能，建议加一个框选
另一个b漫下载软件有下载元数据功能，感觉这里也可以加上，对于存档还是很有用的

### 功能简述

见上文

### 功能逻辑

框选可以是，手动框选，然后点击空格or回车
另一个的元数据样式是这样的
{
  "title": "非人哉",
  "author": "一汪空气,分子互动",
  "artist": "一汪空气,分子互动",
  "description": "据说建国以后妖怪不能成精！那么来一起看看上下五千年来的妖怪是如何适应现代社会的吧！脑洞大开的精彩剧情，不正常的日常生活，一集一个吐槽故事，另类山海经演绎。超人气欢脱条漫可不是说假的哦！\n",
  "genre": [
    "妖怪",
    "神魔",
    "阳光",
    "萌系",
    "搞笑",
    "日常",
    "修真",
    "现代"
  ],
  "status": 1
}

**Comment by Zeal-L** [comment]
- 框选的话是有的，你试试摁住鼠标左键移动覆盖需要下载的章节，然后右键选择勾选
- 元数据功能会考虑在下个版本添加，谢谢建议

**Comment by arashi-knight** [comment]
非常感谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月31日(周三) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zeal-L/BiliBili-Manga-Downloader] [功能请求] 建议添加章节框选功能，建议添加下载漫画元数据的功能 (Issue #39)




  
框选的话是有的，你试试摁住鼠标左键移动覆盖需要下载的章节，然后右键选择勾选
 
元数据功能会考虑在下个版本添加，谢谢建议

**Comment by Zeal-L** [comment]
@arashi-knight 
元数据功能已在新版本中实现 #45
