### ISSUE TITLE
[Bug]  biliplus 可以看未解锁的漫画章节，软件无法下载

### ISSUE THREAD

**Issue by GaryOldMen** [Zeal-L/BiliBili-Manga-Downloader#52]
### 问题描述

biliplus 可以看未解锁的漫画章节，虽然显示灰色但是点击进去可以看
![Snipaste_2023-07-23_00-03-38](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/assets/45043650/29a1ca2e-73fd-4a6b-b2fe-f1e5eed1c42e)
![Snipaste_2023-07-23_00-04-05](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/assets/45043650/aa19d7a8-cceb-47e6-a819-b20f1af1a63b)

软件显示灰色且无法下载
![Snipaste_2023-07-23_00-02-45](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/assets/45043650/d16d84dd-5e7e-4b2a-9baa-af058aa1d5ab)

### 预期行为

无

### 实际行为

无

### 哔哩哔哩漫画下载器版本号

v1.2.0-alpha

### 系统环境

Windows10

### 日志

13:22:29 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

13:26:36 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:36 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:37 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:39 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:42 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:48 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:48 | ERROR | SettingUI: is_cookie_valid - 103 | 重复测试Cookie是否有效多次后失败!
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:26:48 | ERROR | SettingUI: is_cookie_valid - 104 | Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
Traceback (most recent call last):
  File "src\ui\SettingUI.py", line 101, in is_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 93, in _
  File "src\ui\SettingUI.py", line 88, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 369, in prepare
  File "requests\models.py", line 491, in prepare_headers
  File "requests\utils.py", line 1040, in check_header_validity
  File "requests\utils.py", line 1056, in _validate_header_part
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:41 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:41 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:42 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:44 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:47 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:53 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:53 | ERROR | SettingUI: is_cookie_valid - 103 | 重复测试Cookie是否有效多次后失败!
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:27:53 | ERROR | SettingUI: is_cookie_valid - 104 | Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
Traceback (most recent call last):
  File "src\ui\SettingUI.py", line 101, in is_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 93, in _
  File "src\ui\SettingUI.py", line 88, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 369, in prepare
  File "requests\models.py", line 491, in prepare_headers
  File "requests\utils.py", line 1040, in check_header_validity
  File "requests\utils.py", line 1056, in _validate_header_part
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
13:28:17 | INFO | MainGUI: closeEvent - 83 | 

			-------------------  程序正常退出 -------------------

23:07:13 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

23:07:13 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:13 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:14 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:15 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:19 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:25 | WARNING | SettingUI: _ - 92 | 测试Cookie是否有效失败! 重试中...
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:25 | ERROR | SettingUI: is_cookie_valid - 103 | 重复测试Cookie是否有效多次后失败!
Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:07:25 | ERROR | SettingUI: is_cookie_valid - 104 | Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
Traceback (most recent call last):
  File "src\ui\SettingUI.py", line 101, in is_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 93, in _
  File "src\ui\SettingUI.py", line 88, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 369, in prepare
  File "requests\models.py", line 491, in prepare_headers
  File "requests\utils.py", line 1040, in check_header_validity
  File "requests\utils.py", line 1056, in _validate_header_part
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'SESSDATA=5208fa45%2C1705555469%2Cba9af%2A71r_YF5tDsCv_PsiLrlxrHCb2JWlmgvQ0dbJj14ISBNp7F4PRCIi7ErSM4Ujv2SJWTpKXh4wAAEAA\n\n'
23:18:29 | WARNING | SettingUI: _ - 169 | BiliPlus Cookie无效！
23:19:05 | WARNING | SettingUI: _ - 169 | BiliPlus Cookie无效！
23:20:15 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《死神》中...
23:20:15 | INFO | searchComic: getResults - 71 | 搜索结果数量:12
23:20:17 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:20:49 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:15 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:22 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:28 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:32 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:35 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:39 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:42 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:21:43 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:24:06 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:26:21 | INFO | MangaUI: _ - 577 | 开始下载选中章节, 数量: 1
23:30:08 | INFO | MainGUI: closeEvent - 83 | 

			-------------------  程序正常退出 -------------------

23:30:14 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

23:30:20 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:30:25 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:36:53 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:37:01 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:39:53 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《我推的》中...
23:39:53 | INFO | searchComic: getResults - 71 | 搜索结果数量:99
23:39:57 | INFO | MangaUI: updateComicInfo - 370 | 获取《【我推的孩子】》的封面图片中...
23:39:59 | INFO | MangaUI: updateComicInfo - 370 | 获取《【我推的孩子】》的封面图片中...
23:40:07 | INFO | MangaUI: updateComicInfo - 370 | 获取《【我推的孩子】》的封面图片中...
23:40:08 | INFO | MangaUI: updateComicInfo - 370 | 获取《【我推的孩子】》的封面图片中...
23:40:41 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《死神》中...
23:40:42 | INFO | searchComic: getResults - 71 | 搜索结果数量:12
23:40:45 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:40:47 | INFO | MangaUI: updateComicInfo - 370 | 获取《境·界（死神）》的封面图片中...
23:41:10 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《火影》中...
23:41:10 | INFO | searchComic: getResults - 71 | 搜索结果数量:1
23:41:13 | INFO | MangaUI: updateComicInfo - 370 | 获取《火影忍者》的封面图片中...
23:41:17 | INFO | MangaUI: updateComicInfo - 370 | 获取《火影忍者》的封面图片中...
23:59:20 | INFO | MainGUI: closeEvent - 83 | 

			-------------------  程序正常退出 -------------------

00:01:44 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

00:01:51 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
00:01:51 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
00:01:54 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:01:58 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:11 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:12 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:15 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:18 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:21 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:28 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:02:31 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...
00:06:05 | INFO | MainGUI: closeEvent - 83 | 

			-------------------  程序正常退出 -------------------

00:06:12 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

00:06:17 | INFO | MainGUI: closeEvent - 83 | 

			-------------------  程序正常退出 -------------------

00:11:04 | INFO | MainGUI: __init__ - 34 | 

			------------------- 程序启动，初始化主窗口 -------------------

00:11:35 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
00:11:35 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
00:11:39 | INFO | MangaUI: updateComicInfo - 370 | 获取《名侦探柯南》的封面图片中...

**Comment by shadlc** [comment]
@GaryOldMen 已定位到问题，所有超过200话的漫画201话及以后的章节均无法下载，正在处理中( •̀ ω •́ )✧

**Comment by Zeal-L** [comment]
@GaryOldMen 修复后版本已经在内测中了，着急用的话可以先加群下载。正式更新可能还有段时间。

**Comment by GaryOldMen** [comment]
感谢
