### ISSUE TITLE
[功能请求] 建议给文件名增加序号前缀

### ISSUE THREAD

**Issue by MoTingFeng** [Zeal-L/BiliBili-Manga-Downloader#60]
### 原因

在下载之后，按照文件名排序的话，一些特殊的文件名比如番外、特别篇之类的会被单独分出来，不能按照发布顺序阅读

### 功能简述

比如按照章节顺序直接在章节名之前加个001-之类的

### 功能逻辑

按照章节顺序直接在章节名之前加个001-之类的

**Comment by Zeal-L** [comment]
功能是好做，不过这个改动无法先前兼容，也就是说改了后会导致大量用户之前下载的漫画无法被我的库存正确读取。

会考虑在以后的大版本更新中加入，目前能先参考B站的目录吗，不好意思

**Comment by MoTingFeng** [comment]
好的，非常感谢
