### ISSUE TITLE
[Bug] 兄弟，我得告诉你，有B站程序员Star你的项目了

### ISSUE THREAD

**Issue by guowei-gong** [Zeal-L/BiliBili-Manga-Downloader#65]
### 问题描述

因为我 Follow 他，看到了这个项目，白嫖一时爽，担心你被查水表

### 预期行为

暂无

### 实际行为

暂无

### 截图或录屏

暂无

### 哔哩哔哩漫画下载器版本号

暂无

### 系统环境

Windows10

### 日志

暂无

**Comment by Zeal-L** [comment]
emmmm，谢谢提醒。我去把描述改委婉点。
