### ISSUE TITLE
[Bug] 内存泄露！

### ISSUE THREAD

**Issue by Cai-Skirt** [Zeal-L/BiliBili-Manga-Downloader#68]
### 问题描述

下载了大约30话漫画后，软件占用大量内存未释放

### 预期行为

下载完毕后应该释放使用的内存

### 实际行为

软件占用大量内存未释放

### 截图或录屏

<img width="624" alt="捕获" src="https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/53133753/6a7dd085-2fa1-4498-b346-a039e9a67875">

### 哔哩哔哩漫画下载器版本号

v1.3.0

### 系统环境

Windows10

### 日志

21:02:44 | INFO | MainGUI: __init__ - 38 | 

			------------------- 程序启动，初始化主窗口 -------------------

21:03:01 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
21:03:02 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
21:03:05 | INFO | Comic: getComicCover - 125 | 获取《名侦探柯南》的封面图片中...
21:04:42 | INFO | MangaUI: _ - 657 | 开始下载选中章节, 数量: 62
21:07:54 | INFO | MainGUI: closeEvent - 87 | 

			-------------------  程序正常退出 -------------------

15:00:39 | INFO | MainGUI: __init__ - 38 | 

			------------------- 程序启动，初始化主窗口 -------------------

15:00:54 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
15:00:54 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
15:00:56 | INFO | Comic: getComicCover - 125 | 获取《名侦探柯南》的封面图片中...
15:02:03 | INFO | MangaUI: _ - 657 | 开始下载选中章节, 数量: 58
15:05:07 | INFO | MainGUI: closeEvent - 87 | 

			-------------------  程序正常退出 -------------------

15:25:27 | INFO | MainGUI: __init__ - 38 | 

			------------------- 程序启动，初始化主窗口 -------------------

15:31:13 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
15:31:14 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
15:31:17 | INFO | Comic: getComicCover - 125 | 获取《名侦探柯南》的封面图片中...
15:31:27 | INFO | Comic: getComicCover - 125 | 获取《名侦探柯南》的封面图片中...
15:32:00 | INFO | MangaUI: _ - 657 | 开始下载选中章节, 数量: 14
15:38:24 | INFO | MainGUI: closeEvent - 87 | 

			-------------------  程序正常退出 -------------------

15:39:27 | INFO | MainGUI: __init__ - 38 | 

			------------------- 程序启动，初始化主窗口 -------------------

15:39:41 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《柯南》中...
15:39:42 | INFO | searchComic: getResults - 71 | 搜索结果数量:4
15:39:45 | INFO | Comic: getComicCover - 125 | 获取《名侦探柯南》的封面图片中...
15:41:49 | INFO | MangaUI: _ - 657 | 开始下载选中章节, 数量: 27

**Comment by Zeal-L** [comment]
@Cai-Skirt 你选的保存方式是什么呢

**Comment by Cai-Skirt** [comment]
高效！点赞！

**Comment by Zeal-L** [comment]
> 高效！点赞！


嘿嘿，好用的话就给本项目点个star吧，谢谢💖~
