### ISSUE TITLE
[功能请求] 增加额外的导出方式，将整本漫画合并为单个文件

### ISSUE THREAD

**Issue by Nikaidou-Shinku** [Zeal-L/BiliBili-Manga-Downloader#74]
### 原因

我有在电纸书阅读器上阅读漫画的需求，这种情况下将整本漫画合并为单个文件会更加方便。

### 功能简述

将一本漫画的所有页合并进一个 pdf 或 epub，可能的话附带章节标注。

### 功能逻辑

在「设置」选项卡下的「漫画保存格式」中新增该导出方式。

**Comment by Zeal-L** [comment]
本程序只是一个单章批量下载的工具，如果在保存格式中新增这种合并选项并不符合逻辑。~~(非要做的话那就是什么连续追加？)~~
- 你可以考虑搭配README里推荐的 [本地漫画浏览器](https://github.com/Zeal-L/BiliBili-Manga-Downloader#-%E5%8F%8B%E6%83%85%E6%8E%A8%E8%8D%90) 观看。
- 或者可以考虑用PDF下载全部章节后使用其他在线的PDF合并工具合并成单个PDF。我就不重复造轮子了
- 话说单个PDF不知道你有没有仔细想过，比如海贼王全集，那就是几个G的一个PDF，打开速度我不敢想象。
- 又或者可以考虑使用文件夹-图片格式下载后，自行转为需要的格式。
- 目前不论是PDF还是图片格式其实都有附带的章节信息，可以在右键属性中参看。
