### ISSUE TITLE
[Bug] 章节选中计数器异常

### ISSUE THREAD

**Issue by kknd222** [Zeal-L/BiliBili-Manga-Downloader#80]
### 问题描述

我的漫画-本地库存，B站解析后，假设当前是244/245（已下载/全部），勾选章节前的复选框，已选中数会从-1变为0，点击下载无反应
如果点章节名称，则选中数由0变为1
较频发bug

### 预期行为

勾选章节前的复选框，选中数由0变为1

### 实际行为

勾选章节前的复选框，已选中数会从-1变为0，点击下载无反应

### 哔哩哔哩漫画下载器版本号

1.3.2

### 系统环境

Windows10

### 日志

日志未看出异常

**Comment by Zeal-L** [comment]
@kknd222 
这个问题已经在群里被报告过了，也已经得到了解决，会在下个版本中修复。如果着急使用的话可以先到develop分支自行编译
