### ISSUE TITLE
[功能请求] 考虑在每话文件夹前添加序号

### ISSUE THREAD

**Issue by spr-equinox** [Zeal-L/BiliBili-Manga-Downloader#93]
### 原因

以每话标题为文件夹名时，排序会按照拼音顺序排序，若标题为汉字或者作为特殊章节，顺序会乱，如果有特典，会不知道特典跟在哪一话后面
例如《魔女之旅》：
```
第3-话后篇① 筹措资金
第3-话后篇② 筹措资金
第3-话前篇① 筹措资金
第3-话前篇② 筹措资金
第4话·5 该带什么人去无人岛呢？
第4-话后篇① 见习魔女伊蕾娜
```

### 功能简述

保存为
```
001 第3-话前篇① 筹措资金
002 第3-话前篇② 筹措资金
003 第3-话后篇① 筹措资金
004 第3-话后篇② 筹措资金
```

### 功能逻辑

用 `POST` `ComicDetail` 返回的 `JSON` 中章节的 `ord` 数值，插入到文件夹名前

保存格式为 序号+短标题+完整标题

**Comment by Zeal-L** [comment]
@spr-equinox 感谢你的提问，不过这个问题之前在这里被提过 #60 
很遗憾目前暂时还是没有计划添加这个功能
当时其实有尝试过，不过不是每一部漫画的 `ord` 数值都是按照顺序正常排序的，这只能等待B站官方修改了
