### ISSUE TITLE
请问怎么查询哔哩哔哩漫画下漫画id呀？

### ISSUE THREAD

**Issue by BalladeIris** [Zeal-L/BiliBili-Manga-Downloader#96]
### 原因

想要下载已购但已下架的漫画，要通过漫画id下载，但不知道对应的漫画id是怎么搜索到的
https://github.com/Zeal-L/BiliBili-Manga-Downloader/issues/30#issue-1697079652
就是这个问题里的下架漫画下载，它这个笨女孩的漫画id是怎么查询到的呀？

### 功能简述

能告知有其他网站或方法可以给它漫画名称来查询到对应的漫画id吗

### 功能逻辑

无

### 实现参考

无

**Comment by Zeal-L** [comment]
@BalladeIris 
你可以尝试在手机app上打开已购漫画的分享链接，用手机浏览器打开，就可以看到网址，里面就有id

**Comment by BalladeIris** [comment]
> @BalladeIris 你可以尝试在手机app上打开已购漫画的分享链接，用手机浏览器打开，就可以看到网址，里面就有id

好的，谢谢
